version: '3.1'
services:
  app:
    image: golang:alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      testenv: {}
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
    networks:
      testenv: {}
networks:
  testenv:
    external: true
    name: testenv