version: '3.1'
services:
  app:
    image: golang:alpine
    container_name: go-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db
    networks:
      testenv: {}
  db:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
    networks:
      testenv: {}
networks:
  testenv:
    external: true
    name: testenv