// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	Password	string 	`json:"password"`
	Username	string 	`json:"username"`
	IsActive	bool 	`json:"isActive"`
	RoleId		string 	`json:"roleId"`
}
